src/config.h, src/config.rs, src/lib.rs, src/producer.cpp, src/producer.h
librdkafka has been replaced with rust-kafka.
=> Remove configuration settings for librdkafka

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config.rs, src/controller.rs, src/main.rs, src/producer.rs
Add reconnecting logic when giganto server down
Close: #128
=> Send log to giganto

src/producer.rs
receive and print to console ack timestamp
Resolve: #128
=> Receive ack from giganto

CHANGELOG.md, src/producer.rs
=> Check protocol version

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.11.0

CHANGELOG.md, src/controller.rs
=> Add sending line to giganto

CHANGELOG.md, src/producer.rs
- Send channel end message
- Recv channel end ack message
=> Add quic finish logic

Cargo.lock, Cargo.toml, src/producer.rs
=> Update quinn 0.8 to 0.9

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.12.0

src/config.rs, src/controller.rs, src/main.rs
* filtering empty message
* change some help message
=> filtering empty message, change some help message

CHANGELOG.md, Cargo.lock, Cargo.toml, src/config.rs, src/controller.rs, src/lib.rs, src/main.rs, src/producer.rs, src/zeek.rs, src/zeek/conn.rs, src/zeek/dce_rpc.rs, src/zeek/dns.rs, src/zeek/http.rs, src/zeek/kerberos.rs, src/zeek/ntlm.rs, src/zeek/rdp.rs, src/zeek/smtp.rs, src/zeek/ssh.rs
- `conn`, `http`, `rdp`, `smtp`, `dns`
- `ntlm`, `kerberos`, `ssh`, `dce_rpc`
- prints `last line`, `success line`: data line, `failed line`: data line
- `-f` option to read line from given number ( 1 - * )
Close: #180, Close: #182, Close: #183
=> Send raw_event to giganto from zeek log

Cargo.lock, Cargo.toml, src/controller.rs, src/main.rs, src/producer.rs
* Fix clippy error
* change println/eprintln log message to tracing::info/warn/error
=> fix clippy error from rust 1.66

src/controller.rs, src/main.rs, src/producer.rs, src/zeek.rs
- Add zeek grow option
- Modify `-g true` to `-g`
Close: #191
=> Modify grow option

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config.rs, src/controller.rs, src/lib.rs, src/main.rs, src/operation_log.rs, src/producer.rs, src/zeek.rs
=> Send operation log to giganto

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
- Deprecated Kafka server.
Release Issue: #196
=> Release 0.13.0

CHANGELOG.md, src/controller.rs, src/producer.rs
- Allow ctrl-c to zeek log and oplog when the grow option is given.
=> Add ctrlc to zeek, oplog

src/operation_log.rs, src/zeek.rs, src/zeek/tests.rs
- Add oplog testcode
- Add zeek log testcode
=> Add testcode

src/producer.rs, src/zeek/conn.rs, src/zeek/dns.rs
- Parse more field from zeek dns log.
- Parse service field from zeek conn log.
Related: aicers/giganto#241
=> Add more fields

CHANGELOG.md, README.md, src/config.rs, src/controller.rs, src/lib.rs, src/main.rs, src/migration.rs, src/migration/network.rs, src/migration/tests.rs, src/producer.rs, src/zeek.rs
- Add `-m` options to send giganto raw event from giganto export file.
=> Add giganto migration option

src/producer.rs
- Add `version-reproduce` to handshake giganto
=> Modify handshake version

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
- Update protocol version to 0.8.0
Release Issue: #264
=> Release 0.14.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/migration/network.rs, src/migration/tests.rs, src/producer.rs, src/zeek/network.rs, src/zeek/tests.rs
- Support for extended `struct Http` (orig_filenames/orig_mime_types/resp_filenames/resp_mime_types)
- Support for sending `gigaonto`/`zeek` logs for new protocols (`ldap`, `tls`).
=> Add new protocols and extend http field

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
=> Release 0.16.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/migration/network.rs, src/migration/tests.rs, src/producer.rs
=> Add `Mqtt` protocol

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.17.1

CHANGELOG.md, src/producer.rs
=> Add line number to error message

Cargo.lock, Cargo.toml, src/syslog.rs
=> Fixed parse error with default

.github/workflows/ci.yml, Cargo.lock, src/migration.rs, src/migration/network.rs, src/operation_log.rs, src/producer.rs, src/syslog.rs, src/zeek.rs, src/zeek/network.rs
- Modify deprecated function in chrono
=> Fix Clippy error

CHANGELOG.md, Cargo.lock, Cargo.toml, src/migration/network.rs, src/migration/tests.rs, src/zeek/network.rs
Pending https://github.com/aicers/giganto-client/pull/69. Update Cargo.toml after releasing new version of giganto-client.
Close: #399
=> Modify kerberos

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/controller.rs, src/lib.rs, src/netflow.rs, src/netflow/fields.rs, src/netflow/packet.rs, src/netflow/statistics.rs, src/netflow/templates.rs, src/producer.rs
add netflow v5, v9 pcap parser
=> add netflow v5, v9 pcap parser

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version to 0.17.4

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
=> Release 0.17.5

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config.rs, src/controller.rs, src/main.rs, src/producer.rs, src/report.rs, src/syslog.rs, src/syslog/dns_query.rs, src/syslog/file_create.rs, src/syslog/file_create_stream_hash.rs, src/syslog/file_create_time.rs, src/syslog/file_delete.rs, src/syslog/file_delete_detected.rs, src/syslog/image_load.rs, src/syslog/network_connect.rs, src/syslog/pipe_event.rs, src/syslog/process_create.rs, src/syslog/process_tamper.rs, src/syslog/process_terminate.rs, src/syslog/registry_key_rename.rs, src/syslog/registry_value_set.rs, tests/config.toml
- input: elastic
- `-E` option needed for elastic search.
- Added elastic search configuration fields to config file.
Close: #435
=> ElasticSearch to Giganto

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/controller.rs, src/producer.rs, src/syslog.rs, src/syslog/pe_file.rs
This PR is for a feature that is only used in rio projects.
=> Added pe file transfer functionality

Cargo.lock, Cargo.toml, src/migration.rs, src/netflow.rs, src/zeek.rs
=> Update Chrono to 0.4.35 which deprecates method

Cargo.lock, Cargo.toml, src/producer.rs
Close #463
Tis branch에 추가. Giganto에게 이벤트를 100건씩 전송하도록 수정
=> send events in batch

CHANGELOG.md, README.md, src/config.rs, src/producer.rs, tests/config.toml
=> Change `giganto_ingest_addr`to `giganto_ingest_srv_addr`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
=> Release 0.19.0

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.18.0+tis.0.0.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
=> Change the rustls crypto library setting to `aws-lc-rs`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
=> Modify to use ring as the rustls cryptography library option

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/controller.rs, src/migration/network.rs, src/migration/tests.rs, src/producer.rs, src/zeek/network.rs
- Fixed parsing code in zeek log and giganto log due to changes in conn.
- Support for sending `giganto` log for new protocols. (`Bootp`,`Dhcp`).
- Changed `GIGANTO_VERSION` to "0.21.0".
- Update README.md and CHANGELOG.md
Close: #506
=> Support giganto-client 0.20.0

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.20.0

CHANGELOG.md, src/migration/network.rs
=> Fix empty value of vector type from `vec![0]` to `Vec::new()`

CHANGELOG.md, README.md, src/config.rs, src/producer.rs, tests/config.toml
=> Change `root` to `ca_certs` to handle multiple certs

CHANGELOG.md, src/producer.rs
=> Correct giganto version name

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version to 0.20.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/operation_log.rs
=> Added sensor field to OpLog

CHANGELOG.md, Cargo.lock, Cargo.toml, src/netflow/packet.rs, src/security_log/aiwaf.rs, src/security_log/axgate.rs, src/security_log/fgt.rs, src/security_log/mf2.rs, src/security_log/nginx.rs, src/security_log/shadow_wall.rs, src/security_log/sniper_ips.rs, src/security_log/sonic_wall.rs, src/security_log/srx.rs, src/security_log/tg.rs, src/security_log/ubuntu.rs, src/security_log/vforce.rs, src/security_log/wapples.rs
=> Remove deleted `source` within the `Netflow5`, `Netflow9`, `SecuLog`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/producer.rs
=> Bump version to 0.21.0

src/producer.rs
=> Fix Clippy warnings caused by rustc 1.84.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config.rs, src/main.rs, src/netflow/packet.rs
Added `log_dir` configuration for saving logs.
Closes #539
=> Adjust logging behavior

CHANGELOG.md, src/controller.rs, src/producer.rs, src/report.rs
=> Extend report statistics to all logs

.cargo/config.toml, CHANGELOG.md, README.md, src/main.rs
Added the env variable `LOG_FILENAME` to the Cargo config file.
Closes #574
=> Rename the log file

README.md
=> Reformat README with Markdown rules

src/main.rs
- Removed dependency on build type
Close: #591
=> Log to file if log_path set, otherwise stdout

src/main.rs
=> Fix comment on `init_tracing` function.

CHANGELOG.md, Cargo.lock, Cargo.toml
Issue #601 
- Updating the bincode crate will be covered in a separate issue
- No changes to the COMPATIBLE version are required.
=> Release 0.22.0

CHANGELOG.md, README.md
=> Fix Markdown format errors introduced by Prettier

README.md
=> Scope markdownlint disable by rule

CHANGELOG.md, Cargo.lock, Cargo.toml
Issue #611 
- Updating the bincode crate will be covered in a separate issue
- No changes to the COMPATIBLE version are required.
=> Release 0.22.1
